/**
 * 500 inspirational affirmations for the habit tracking app
 * Organized by themes: gratitude, confidence, growth, peace, strength, success, health, relationships
 */

export const affirmationsData = [
  // Gratitude (60)
  "I am grateful for all the blessings in my life",
  "Gratitude fills my heart with joy and peace",
  "I appreciate the beauty around me every day",
  "I am thankful for my health and vitality",
  "Every day brings new reasons to be grateful",
  "I celebrate the good in my life",
  "I am blessed beyond measure",
  "Gratitude transforms my perspective",
  "I notice and appreciate the small miracles",
  "I am thankful for my loved ones",
  "Appreciation is a daily practice for me",
  "I recognize the abundance in my life",
  "I am grateful for challenges that help me grow",
  "Thank you for all the love in my life",
  "I cherish every moment of this day",
  "Gratitude is my natural state",
  "I am thankful for my unique gifts",
  "I appreciate my own strength",
  "I am grateful for second chances",
  "Today I choose gratitude",
  "I thank myself for my efforts",
  "I am blessed with wonderful opportunities",
  "Gratitude brings me closer to happiness",
  "I appreciate my journey and where I am",
  "I am grateful for peaceful moments",
  "I count my blessings daily",
  "I celebrate progress, not perfection",
  "I am thankful for my ability to learn",
  "I appreciate the love I give and receive",
  "I am grateful for my resilience",
  "I am blessed to be alive",
  "I appreciate my body and its capabilities",
  "I am thankful for true friends",
  "I recognize beauty in everyday moments",
  "I am grateful for my potential",
  "I appreciate the growth I've achieved",
  "I am blessed with abundance",
  "I am thankful for my choices",
  "I appreciate my sense of humor",
  "I am grateful for rest and recovery",
  "I celebrate my accomplishments",
  "I am thankful for this present moment",
  "I appreciate my courage",
  "I am grateful for new beginnings",
  "I am blessed with inner peace",
  "I am thankful for my creativity",
  "I appreciate my unique perspective",
  "I am grateful for joy in simple things",
  "I recognize the gifts I've been given",
  "I am thankful for my determination",
  "I appreciate life's lessons",
  "I am grateful for love",
  "I am blessed beyond my wildest dreams",
  "I am thankful for my intuition",
  "I appreciate my compassion",
  "I am grateful for growth and healing",
  "I am thankful for this breath",
  "I appreciate my journey",
  "I am grateful for my heart",
  "I celebrate all that I am",
  "I am blessed to have this day",

  // Confidence (60)
  "I am confident in my abilities",
  "I believe in myself completely",
  "I am capable of achieving my goals",
  "I have the power to create change",
  "I trust myself to make good decisions",
  "I am worthy of success",
  "My confidence grows every day",
  "I am brave and bold",
  "I trust my instincts",
  "I am strong and resilient",
  "I believe in my potential",
  "I am enough, just as I am",
  "I face challenges with confidence",
  "I am self-assured and capable",
  "I trust in my abilities",
  "I am a person of strength",
  "I believe in my dreams",
  "I am confident in my choices",
  "I am worthy of good things",
  "I stand tall and proud",
  "I trust my journey",
  "I am capable and competent",
  "I believe in my future",
  "I am bold and fearless",
  "I have what it takes",
  "I am confident in my power",
  "I trust my worthiness",
  "I am deserving of success",
  "I believe in my vision",
  "I am capable of growth",
  "I am self-assured",
  "I believe in my strength",
  "I am confident in my path",
  "I trust my inner wisdom",
  "I am worthy of my dreams",
  "I am brave enough to try",
  "I believe in my talent",
  "I am capable of excellence",
  "I trust in my progress",
  "I am confident in who I am",
  "I believe in my heart",
  "I am strong in my convictions",
  "I trust my ability to succeed",
  "I am worthy of confidence",
  "I believe in my intelligence",
  "I am capable of amazing things",
  "I am confident in my spirit",
  "I trust myself completely",
  "I am worthy of achievement",
  "I believe in my power",
  "I am capable and brilliant",
  "I am confident in my direction",
  "I trust my instincts completely",
  "I am worthy of greatness",
  "I believe in my capacity",
  "I am strong and sure",
  "I am confident in my choices",
  "I trust my path",
  "I am worthy of all good things",
  "I believe in my success",
  "I am capable of my dreams",

  // Growth (60)
  "I am constantly evolving and growing",
  "I embrace change and transformation",
  "I am learning and becoming stronger",
  "Every challenge helps me grow",
  "I am expanding my potential",
  "I welcome new experiences",
  "I am becoming my best self",
  "Growth is my natural state",
  "I am developing new skills",
  "I am improving every day",
  "I am open to transformation",
  "I embrace my potential",
  "I am growing wiser",
  "I am becoming more resilient",
  "I welcome personal development",
  "I am expanding my horizons",
  "I embrace learning",
  "I am becoming more confident",
  "I am developing my talents",
  "I am growing in strength",
  "I am becoming more authentic",
  "I embrace challenges for growth",
  "I am expanding my mind",
  "I am growing into my power",
  "I am becoming more aware",
  "I welcome change",
  "I am developing my gifts",
  "I am growing stronger each day",
  "I am becoming better",
  "I embrace my evolution",
  "I am expanding my consciousness",
  "I am growing in wisdom",
  "I welcome transformation",
  "I am developing inner strength",
  "I am becoming more aligned",
  "I am expanding my capabilities",
  "I embrace my journey",
  "I am growing spiritually",
  "I am becoming more compassionate",
  "I welcome growth opportunities",
  "I am developing my purpose",
  "I am expanding my love",
  "I am growing into myself",
  "I embrace my potential fully",
  "I am becoming my vision",
  "I welcome new perspectives",
  "I am developing my voice",
  "I am growing in gratitude",
  "I embrace change with grace",
  "I am expanding my joy",
  "I am growing in self-love",
  "I welcome progress",
  "I am developing confidence",
  "I am expanding my impact",
  "I embrace my authentic self",
  "I am becoming wiser",
  "I welcome abundance",
  "I am developing my path",
  "I am growing towards my dreams",
  "I welcome my evolution",

  // Peace (60)
  "I am at peace with myself",
  "Peace flows through me",
  "I find calm in every moment",
  "I am serene and centered",
  "I choose peace over worry",
  "Inner peace is my birthright",
  "I am grounded and calm",
  "Peace fills my heart",
  "I let go of what I cannot control",
  "I am peaceful and content",
  "I find stillness within",
  "I am at ease",
  "I breathe in peace",
  "My mind is calm and clear",
  "I am centered in my truth",
  "I choose tranquility",
  "I am present and peaceful",
  "I let go of anxiety",
  "I find peace in simplicity",
  "I am balanced and calm",
  "I release tension",
  "I am peaceful within",
  "I find peace in acceptance",
  "I am quiet and still",
  "I embrace serenity",
  "I am at peace with my past",
  "I find calm in uncertainty",
  "I am mindful and present",
  "I choose inner peace",
  "I am peaceful and free",
  "I let go of control",
  "I find peace in surrender",
  "I am calm and collected",
  "I am at peace with change",
  "I find stillness within",
  "I am peaceful by nature",
  "I release worry",
  "I find peace in trust",
  "I am centered and strong",
  "I choose calm responses",
  "I am at peace with myself",
  "I find tranquility",
  "I am peaceful and powerful",
  "I let go of judgment",
  "I find peace in now",
  "I am grounded in peace",
  "I choose serenity",
  "I am at ease with life",
  "I find calm naturally",
  "I am peaceful and resilient",
  "I release the need to control",
  "I find peace in my heart",
  "I am centered and clear",
  "I am peaceful always",
  "I find ease in acceptance",
  "I am calm and capable",
  "I choose peace always",
  "I find stillness easily",
  "I am at peace now",

  // Strength (60)
  "I am strong and capable",
  "My strength grows daily",
  "I am resilient and powerful",
  "I have inner strength",
  "I am unbreakable",
  "My power is immense",
  "I am strong in my convictions",
  "I overcome obstacles",
  "I am mighty and strong",
  "My strength is my superpower",
  "I am strong through hardship",
  "I have the strength to succeed",
  "I am powerful and capable",
  "I rise above challenges",
  "I am strong in my purpose",
  "My resilience is unmatched",
  "I am strong and steady",
  "I power through difficulties",
  "I have strength within",
  "I am strong of character",
  "I embrace my power",
  "I am strong and determined",
  "I overcome with ease",
  "I am strong in my belief",
  "My inner strength sustains me",
  "I am powerful beyond measure",
  "I am strong and calm",
  "I overcome any challenge",
  "I have deep reserves of strength",
  "I am strong and brave",
  "I power through fear",
  "I am strong of spirit",
  "I rise stronger",
  "I am mighty in my purpose",
  "I have unlimited strength",
  "I am strong and wise",
  "I overcome with strength",
  "I am powerful in my choices",
  "I have strength to give",
  "I am strong always",
  "My strength is my gift",
  "I am unshakeable",
  "I overcome with grace",
  "I am strong beyond measure",
  "I tap into my power",
  "I am strong and worthy",
  "I power my dreams",
  "I am strong in adversity",
  "I have immense strength",
  "I am powerful and kind",
  "I overcome challenges easily",
  "I am strong in my truth",
  "My strength flows freely",
  "I am powerful and peaceful",
  "I am strong in my heart",
  "I overcome with love",
  "I am mighty and kind",
  "I have strength to share",
  "I am powerfully alive",

  // Success (60)
  "I am successful",
  "Success flows to me naturally",
  "I achieve my goals",
  "I am a success",
  "I manifest my dreams",
  "I am destined for success",
  "My success is inevitable",
  "I create success",
  "I attract prosperity",
  "I am a winner",
  "I succeed in all I do",
  "My potential is limitless",
  "I achieve excellence",
  "I am successful and fulfilled",
  "I attract success",
  "I move toward my goals",
  "I am successful always",
  "I create abundance",
  "I attract good fortune",
  "I achieve my vision",
  "I am successful by design",
  "I create my success",
  "I manifest abundance",
  "I move forward with ease",
  "I am successful in all ways",
  "I attract opportunities",
  "I achieve everything",
  "I am a brilliant success",
  "I create prosperity",
  "I attract what I want",
  "I achieve my dreams",
  "I am successful today",
  "I create my future",
  "I manifest my desires",
  "I achieve with ease",
  "I am successful always",
  "I attract greatness",
  "I achieve success",
  "I create amazing things",
  "I attract abundance easily",
  "I move toward excellence",
  "I am successful in everything",
  "I create what I want",
  "I manifest my best life",
  "I achieve my vision",
  "I attract success easily",
  "I am destined for greatness",
  "I create my destiny",
  "I manifest prosperity",
  "I achieve with confidence",
  "I am successful always",
  "I attract good things",
  "I achieve my purpose",
  "I create excellence",
  "I manifest my power",
  "I achieve success daily",
  "I attract my dreams",
  "I am successful beyond measure",
  "I create abundance daily",
  "I manifest amazing success",

  // Health (60)
  "I am healthy and vibrant",
  "My body is strong and capable",
  "I am filled with energy",
  "I am in perfect health",
  "I love my body",
  "I am healthy and whole",
  "My health is improving",
  "I am strong and healthy",
  "I am vibrant with life",
  "I am healthy inside and out",
  "I radiate health",
  "I am full of vitality",
  "I am healthy and happy",
  "I feel amazing",
  "I am healing completely",
  "I am healthy always",
  "I am strong and fit",
  "I am energized and healthy",
  "I feel wonderful",
  "I am vibrant and alive",
  "I am healthy by nature",
  "I feel my best",
  "I am rejuvenated and healthy",
  "I am brimming with health",
  "I am healthy and glowing",
  "I radiate vitality",
  "I am strong and resilient",
  "I feel fantastic",
  "I am healthy and balanced",
  "I am full of life",
  "I am completely healthy",
  "I am energetic and strong",
  "I feel alive and well",
  "I am healthy and thriving",
  "I am vitalized",
  "I am healthy through and through",
  "I feel incredible",
  "I am strong and vital",
  "I am glowing with health",
  "I am healthy every day",
  "I feel blessed with health",
  "I am healing wonderfully",
  "I am healthy and free",
  "I feel amazing daily",
  "I am bursting with health",
  "I am strong and healthy",
  "I feel wonderful always",
  "I am healthy inside",
  "I am vibrant and healthy",
  "I feel my power",
  "I am perfectly healthy",
  "I am healing daily",
  "I feel strong and capable",
  "I am healthy and beautiful",
  "I am radiating health",
  "I feel vitality flowing",
  "I am healthy always",
  "I am feeling wonderful",
  "I am strong and well",
  "I feel completely alive",

  // Relationships (60)
  "I attract loving relationships",
  "I am deserving of love",
  "I give and receive love freely",
  "I am surrounded by love",
  "I am loved and appreciated",
  "I attract genuine connections",
  "I am a loving person",
  "I attract positive people",
  "I am worthy of friendship",
  "I am kind and compassionate",
  "I attract love naturally",
  "I am love",
  "I give love generously",
  "I am loved deeply",
  "I attract supportive people",
  "I am open to love",
  "I am a good friend",
  "I attract healthy relationships",
  "I am worthy of affection",
  "I love myself completely",
  "I attract like-minded people",
  "I am loving and kind",
  "I receive love easily",
  "I am surrounded by support",
  "I attract true friends",
  "I am genuinely connected",
  "I give unconditional love",
  "I am loved for who I am",
  "I attract meaningful relationships",
  "I am worthy of respect",
  "I love with my whole heart",
  "I am appreciated deeply",
  "I attract loving people",
  "I am open to connection",
  "I am a valuable friend",
  "I attract compatible people",
  "I am kind and loving",
  "I receive love gratefully",
  "I am cherished and valued",
  "I attract authentic connections",
  "I am genuinely liked",
  "I give love easily",
  "I am loved unconditionally",
  "I attract supportive friends",
  "I am worthy of devotion",
  "I love myself and others",
  "I am deeply appreciated",
  "I attract caring people",
  "I am open and vulnerable",
  "I am a true friend",
  "I attract beautiful relationships",
  "I am loved for my authenticity",
  "I attract harmony",
  "I am kind to myself",
  "I receive support easily",
  "I am surrounded by love",
  "I attract mutual respect",
  "I am genuinely valued",
  "I give and receive love",
];

export default affirmationsData;
