import React,{useCallback,useRef,useState} from 'react';
import {Alert,KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {useRouter,useFocusEffect} from 'expo-router';
import {getJournalEntriesForDate,createJournalEntry,updateJournalEntry} from '@/utils/database';
import {getLocalDateKey} from '@/utils/planner';
import {useTheme} from '@/contexts/ThemeContext';
type SpeechModule=typeof import('expo-speech-recognition').ExpoSpeechRecognitionModule;
function SpeechEvents({onResult,onEnd,onError}:{onResult:(e:any)=>void;onEnd:()=>void;onError:(e:any)=>void}){ // loaded only while reflection route is open
 // eslint-disable-next-line @typescript-eslint/no-require-imports
 const {useSpeechRecognitionEvent}=require('expo-speech-recognition') as typeof import('expo-speech-recognition');
 useSpeechRecognitionEvent('result',onResult);useSpeechRecognitionEvent('end',onEnd);useSpeechRecognitionEvent('error',onError);return null;
}
export default function ReflectionScreen(){const router=useRouter();const{isDark}=useTheme();const date=getLocalDateKey();const [content,setContent]=useState('');const [entryId,setEntryId]=useState<string|null>(null);const[recording,setRecording]=useState(false);const[busy,setBusy]=useState(false);const base=useRef('');const dark=isDark;
 const load=useCallback(async()=>{const rows=await getJournalEntriesForDate(date) as any[];if(rows[0]){setContent(rows[0].content||'');setEntryId(rows[0].id)}},[date]);useFocusEffect(useCallback(()=>{void load()},[load]));
 const save=async()=>{setBusy(true);try{if(entryId)await updateJournalEntry(entryId,{content});else{const id=`journal_${Date.now()}`;await createJournalEntry({id,content,date});setEntryId(id)}Alert.alert('Saved','Your reflection is saved on this device.')}catch{Alert.alert('Could not save','Try again in a moment.')}finally{setBusy(false)}};
 const start=async()=>{try{// eslint-disable-next-line @typescript-eslint/no-require-imports
 const{ExpoSpeechRecognitionModule}=require('expo-speech-recognition') as {ExpoSpeechRecognitionModule:SpeechModule};if(!ExpoSpeechRecognitionModule.isRecognitionAvailable())return Alert.alert('Dictation unavailable','Turn on Speech Recognition or Siri & Dictation in device settings.');const p=await ExpoSpeechRecognitionModule.requestPermissionsAsync();if(!p.granted)return Alert.alert('Permission required','Allow microphone and speech recognition access to dictate.');base.current=content.trim()?`${content.trim()} `:'';ExpoSpeechRecognitionModule.start({lang:'en-US',interimResults:true,continuous:false,iosTaskHint:'dictation'});setRecording(true)}catch{Alert.alert('Dictation unavailable','Please try again.')}};
 const onResult=(e:any)=>{const transcript=e?.results?.[0]?.transcript;if(transcript)setContent(`${base.current}${transcript}`)};
 return <KeyboardAvoidingView style={{flex:1,backgroundColor:dark?'#0A102C':'#F4F6FF'}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.page}>{recording&&<SpeechEvents onResult={onResult} onEnd={()=>setRecording(false)} onError={()=>setRecording(false)}/>}<Pressable onPress={()=>router.back()}><Text style={s.back}>‹  Back</Text></Pressable><Text style={[s.date,{color:dark?'#AFC0FF':'#69749A'}]}>{new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}</Text><Text style={[s.title,{color:dark?'white':'#111943'}]}>Daily reflection</Text><Text style={[s.prompt,{color:dark?'#C9D3F3':'#4D587C'}]}>A moment to reflect</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12}}>{['What went well?','What could improve?','What is tomorrow’s priority?'].map(prompt=><Pressable key={prompt} onPress={()=>setContent(prev=>prev.trim()?`${prev.trim()}\n\n${prompt}\n`: `${prompt}\n`)} style={{backgroundColor:dark?'#17234B':'#E8EDFF',paddingHorizontal:12,paddingVertical:9,borderRadius:16}}><Text style={{color:dark?'#DCE5FF':'#4059A4',fontSize:12,fontWeight:'600'}}>{prompt}</Text></Pressable>)}</View><Text style={[s.hint,{color:dark?'#9DA9CC':'#7F89A8'}]}>Write a little or a lot. Your reflection stays on this device.</Text><TextInput multiline textAlignVertical="top" value={content} onChangeText={setContent} placeholder="Today, I noticed…" placeholderTextColor="#929BB4" style={[s.input,{backgroundColor:dark?'#141D42':'white',color:dark?'white':'#151C45'}]}/><Pressable onPress={recording?()=>{ // eslint-disable-next-line @typescript-eslint/no-require-imports
 try{const{ExpoSpeechRecognitionModule}=require('expo-speech-recognition') as {ExpoSpeechRecognitionModule:SpeechModule};ExpoSpeechRecognitionModule.stop()}catch{}setRecording(false)}:start} style={[s.secondary,recording&&{backgroundColor:'#FFF0F1'}]}><Text style={{color:recording?'#D8445B':'#426CFF',fontWeight:'700'}}>{recording?'■  Stop dictation':'🎙  Dictate reflection'}</Text></Pressable><Pressable disabled={busy} onPress={save} style={s.button}><Text style={s.buttonText}>{busy?'Saving…':'Save reflection'}</Text></Pressable></ScrollView></KeyboardAvoidingView>}
const s=StyleSheet.create({page:{padding:22,paddingTop:20,paddingBottom:40},back:{color:'#456AFF',fontWeight:'700',fontSize:16,marginBottom:32},date:{fontSize:11,fontWeight:'800',letterSpacing:1.2},title:{fontSize:32,fontWeight:'800',marginTop:8},prompt:{fontSize:19,fontWeight:'600',marginTop:27},hint:{fontSize:13,lineHeight:19,marginTop:8},input:{height:250,borderRadius:20,padding:17,fontSize:16,lineHeight:24,marginTop:20},secondary:{borderWidth:1,borderColor:'#D5DCFA',borderRadius:14,padding:15,alignItems:'center',marginTop:13},button:{backgroundColor:'#426CFF',borderRadius:14,padding:16,alignItems:'center',marginTop:12},buttonText:{color:'white',fontWeight:'700',fontSize:16}});
