import React,{useCallback,useEffect,useState} from 'react';
import {LinearGradient} from 'expo-linear-gradient';
import {Alert,Modal,Pressable,ScrollView,StyleSheet,Switch,Text,TextInput,View} from 'react-native';
import {useFocusEffect,useLocalSearchParams, useRouter} from 'expo-router';
import {useTheme} from '@/contexts/ThemeContext';
import {addPlannedItem,deletePlannedItem,getLocalDateKey,getPlanForDate,makeId,PlanEntry,setPlannedItemCompleted,getDayCompletion} from '@/utils/planner';
import {setHabitCompletion} from '@/utils/database';
import {scheduleTaskReminder,cancelTaskReminder} from '@/utils/notifications';
const days=['S','M','T','W','T','F','S'];
const plus=(key:string,n:number)=>{const d=new Date(`${key}T12:00:00`);d.setDate(d.getDate()+n);return getLocalDateKey(d)};
const shiftMonth=(key:string,delta:number)=>{const d=new Date(`${key}T12:00:00`);return getLocalDateKey(new Date(d.getFullYear(),d.getMonth()+delta,1,12))};
export default function CalendarScreen(){
 const {isDark}=useTheme();const router=useRouter();const params=useLocalSearchParams<{date?:string;item?:string}>();
 const today=getLocalDateKey();const[date,setDate]=useState(params.date||today);const[view,setView]=useState<'Day'|'Week'|'Month'>('Day');const[items,setItems]=useState<PlanEntry[]>([]);const[monthCounts,setMonthCounts]=useState<Record<string,{completed:number;total:number}>>({});const[modal,setModal]=useState(false);const[title,setTitle]=useState('');const[time,setTime]=useState('');const[reminderEnabled,setReminderEnabled]=useState(false);const dark=isDark;const text='#FFFFFF';
 useEffect(()=>{if(params.date)setDate(params.date)},[params.date]);
 const load=useCallback(async()=>{const p=await getPlanForDate(date);setItems(p)},[date]);useFocusEffect(useCallback(()=>{void load()},[load]));
 useEffect(()=>{if(view!=='Month')return;let active=true;const loadMonth=async()=>{const d=new Date(`${date}T12:00:00`);const n=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();const dates=Array.from({length:n},(_,i)=>getLocalDateKey(new Date(d.getFullYear(),d.getMonth(),i+1,12)));const plans=await Promise.all(dates.map(k=>getPlanForDate(k)));if(active){const values:typeof monthCounts={};dates.forEach((k,i)=>values[k]=getDayCompletion(plans[i]));setMonthCounts(values)}};void loadMonth();return()=>{active=false}},[date,view]);
 const toggle=async(i:PlanEntry)=>{const completed=!i.completed;if(i.kind==='habit'&&i.habitId)await setHabitCompletion(i.habitId,date,completed);if(i.kind==='task'&&i.taskId)await setPlannedItemCompleted(i.taskId,date,completed);await load()};
 const save=async()=>{const clean=title.trim();if(!clean)return Alert.alert('Add a name','Enter a name for this task.');if(time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))return Alert.alert('Check the time','Use 24-hour time, such as 14:30.');const id=makeId('task');const notified=reminderEnabled&&!!time?await scheduleTaskReminder(id,clean,date,time):false;await addPlannedItem({id,title:clean,date,time,reminderEnabled:notified});if(reminderEnabled&&time&&!notified)Alert.alert('Reminder not set','The task was added, but its reminder could not be scheduled. Check the time and notification permission.');setTitle('');setTime('');setReminderEnabled(false);setModal(false);await load()};
 const counts=getDayCompletion(items);const monthDate=new Date(`${date}T12:00:00`);
 return <LinearGradient colors={['#111A78','#1455D9','#23B9EB']} start={{x:0,y:0}} end={{x:0,y:1}} style={{flex:1}}><View style={s.page}><ScrollView contentContainerStyle={s.body}>
 <Text style={[s.title,{color:text}]}>Calendar</Text><View style={s.switch}>{(['Day','Week','Month'] as const).map(v=><Pressable key={v} onPress={()=>setView(v)} style={[s.pill,view===v&&s.active]}><Text style={{color:view===v?'#4057DD':'white',fontWeight:'700'}}>{v}</Text></Pressable>)}</View>
 {view==='Day'&&<><View style={s.dateRow}><Pressable onPress={()=>setDate(plus(date,-1))}><Text style={s.nav}>‹</Text></Pressable><Pressable onPress={()=>setDate(today)}><Text style={[s.dateText,{color:text}]}>{date===today?'Today':new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</Text></Pressable><Pressable onPress={()=>setDate(plus(date,1))}><Text style={s.nav}>›</Text></Pressable></View><Text style={s.summary}>{counts.completed} of {counts.total} habits and tasks complete</Text><View style={s.timeline}>{items.length?items.map(i=><Pressable key={i.id} onPress={()=>toggle(i)} onLongPress={()=>i.taskId&&Alert.alert('Delete task?',i.title,[{text:'Cancel'},{text:'Delete',style:'destructive',onPress:async()=>{await deletePlannedItem(i.taskId!);await cancelTaskReminder(i.taskId!);load()}}])} style={[s.entry,{backgroundColor:dark?'#141D42':'white'},(i.habitId===params.item||i.taskId===params.item)&&{borderColor:'#426CFF',borderWidth:2}]}><View style={[s.dot,{backgroundColor:i.color||'#4B73FF'}]}/><Text style={s.time}>{i.time||'Any time'}</Text><View style={{flex:1}}><Text style={[s.entryTitle,{color:text,textDecorationLine:i.completed?'line-through':'none'}]}>{i.title}</Text><Text style={s.meta}>{i.kind==='task'?'Task':i.kind==='habit'?'Habit':'Affirmation'}</Text></View><Text style={{fontSize:18,color:i.completed?'#1BAC82':'#A7B1C9'}}>{i.completed?'✓':'○'}</Text></Pressable>):<Text style={s.empty}>Nothing planned yet. Add a task or set up a habit.</Text>}</View></>}
 {view==='Week'&&<View>{Array.from({length:7},(_,n)=>plus(date,n-new Date(`${date}T12:00:00`).getDay())).map(key=>{const weekday=new Date(`${key}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});return <WeekRow key={key} date={key} label={weekday} today={key===today} dark={dark} text={'#151C45'} onPress={()=>{setDate(key);setView('Day')}}/>})}</View>}
 {view==='Month'&&<><View style={s.monthHead}><Pressable onPress={()=>setDate(shiftMonth(date,-1))}><Text style={s.nav}>‹</Text></Pressable><Text style={[s.dateText,{color:text}]}>{monthDate.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</Text><Pressable onPress={()=>setDate(shiftMonth(date,1))}><Text style={s.nav}>›</Text></Pressable></View><View style={s.grid}>{days.map((d,i)=><Text key={`d${i}`} style={s.dayLabel}>{d}</Text>)}{(()=>{const start=new Date(monthDate.getFullYear(),monthDate.getMonth(),1).getDay();const count=new Date(monthDate.getFullYear(),monthDate.getMonth()+1,0).getDate();return [...Array(start).fill(null),...Array.from({length:count},(_,i)=>i+1)].map((day:any,i)=>{const key=day?getLocalDateKey(new Date(monthDate.getFullYear(),monthDate.getMonth(),day,12)):'';const stat=monthCounts[key];return <Pressable key={i} disabled={!day} onPress={()=>{setDate(key);setView('Day')}} style={[s.cell,day&&key===date&&s.selected]}><Text style={{color:key===date?'white':text,fontWeight:key===today?'800':'500'}}>{day||''}</Text>{day&&stat?.total>0&&<View style={[s.activityDot,{backgroundColor:key===date?'white':stat.completed===stat.total?'#20B987':'#7B96FF'}]}/>}</Pressable>})})()}</View><Text style={s.monthHint}>Dots show planned activity · green means everything is complete</Text></>}
 <Pressable onPress={()=>{setTitle('');setTime('');setReminderEnabled(false);setModal(true)}} style={s.add}><Text style={s.addText}>＋ Add one-time task</Text></Pressable>
 </ScrollView><Modal visible={modal} transparent animationType="slide" onRequestClose={()=>setModal(false)}><View style={s.scrim}><View style={s.sheet}><Text style={[s.title,{color:text,fontSize:23}]}>New task</Text><Text style={s.meta}>For {date}</Text><TextInput value={title} onChangeText={setTitle} placeholder="What do you need to do?" placeholderTextColor="#8A93AE" style={s.input}/><TextInput value={time} onChangeText={setTime} placeholder="Time (optional, e.g. 14:30)" placeholderTextColor="#8A93AE" style={s.input}/><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:13}}><Text style={{color:'#354166',fontWeight:'600'}}>Remind me</Text><Switch value={reminderEnabled} onValueChange={setReminderEnabled}/></View><Pressable style={s.add} onPress={save}><Text style={s.addText}>Add to calendar</Text></Pressable><Pressable onPress={()=>setModal(false)}><Text style={[s.meta,{textAlign:'center',padding:12}]}>Cancel</Text></Pressable></View></View></Modal></View></LinearGradient>
}
function WeekRow({date,label,today,dark,text,onPress}:{date:string;label:string;today:boolean;dark:boolean;text:string;onPress:()=>void}){const[stat,setStat]=useState({completed:0,total:0});useEffect(()=>{let active=true;getPlanForDate(date).then(p=>{if(active)setStat(getDayCompletion(p))});return()=>{active=false}},[date]);const pct=stat.total?stat.completed/stat.total:0;return <Pressable onPress={onPress} style={[s.weekRow,{backgroundColor:dark?'#141D42':'white'}]}><View style={{flex:1}}><Text style={[s.weekTitle,{color:text}]}>{today?'Today':label}</Text><Text style={s.meta}>{stat.total?`${stat.completed}/${stat.total} complete`:'No items scheduled'}</Text></View><View style={s.bar}><View style={[s.barFill,{width:`${Math.round(pct*100)}%`}]}/></View><Text style={s.meta}>›</Text></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'transparent'},body:{padding:20,paddingBottom:115},title:{fontSize:32,fontWeight:'800',marginBottom:18},switch:{flexDirection:'row',backgroundColor:'rgba(255,255,255,.22)',padding:4,borderRadius:13},pill:{flex:1,alignItems:'center',padding:10,borderRadius:10},active:{backgroundColor:'white'},dateRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginVertical:22},dateText:{fontSize:17,fontWeight:'700'},nav:{fontSize:30,color:'#456AFF',paddingHorizontal:9},timeline:{gap:9},entry:{borderRadius:15,padding:14,flexDirection:'row',alignItems:'center',gap:10},dot:{width:9,height:9,borderRadius:5},time:{width:62,fontSize:12,color:'#8791AF'},entryTitle:{fontSize:14,fontWeight:'700'},meta:{fontSize:12,color:'#8C96B3',marginTop:4},summary:{fontSize:13,color:'#DCE8FF',marginBottom:12},empty:{padding:20,textAlign:'center',color:'#DCE8FF'},add:{backgroundColor:'#426CFF',borderRadius:14,padding:15,alignItems:'center',marginTop:18},addText:{color:'white',fontWeight:'700',fontSize:15},weekRow:{padding:16,borderRadius:14,marginTop:8,flexDirection:'row',alignItems:'center',gap:15},weekTitle:{fontSize:15,fontWeight:'700'},bar:{height:6,width:74,backgroundColor:'#E7EAF6',borderRadius:5,overflow:'hidden'},barFill:{height:6,backgroundColor:'#426CFF',borderRadius:5},monthHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginVertical:16},grid:{flexDirection:'row',flexWrap:'wrap'},dayLabel:{width:'14.28%',textAlign:'center',color:'#DCE8FF',padding:8,fontWeight:'700'},cell:{width:'14.28%',aspectRatio:1,alignItems:'center',justifyContent:'center',borderRadius:30},selected:{backgroundColor:'#426CFF'},activityDot:{width:5,height:5,borderRadius:3,marginTop:2},monthHint:{fontSize:12,color:'#DCE8FF',textAlign:'center',marginTop:9},scrim:{flex:1,backgroundColor:'#0008',justifyContent:'flex-end'},sheet:{backgroundColor:'#fff',padding:22,paddingBottom:35,borderTopLeftRadius:25,borderTopRightRadius:25},input:{borderWidth:1,borderColor:'#DCE1EF',borderRadius:12,padding:13,color:'#141A3E',marginTop:13}});
