import React,{useCallback,useState} from 'react';
import {Alert,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {useFocusEffect} from 'expo-router';
import {useTheme} from '@/contexts/ThemeContext';
import {addPlannedItem,deletePlannedItem,getLocalDateKey,getPlanForDate,makeId,PlanEntry,setHabitCompletion,setPlannedItemCompleted} from '@/utils/planner';
const days=['S','M','T','W','T','F','S'];
const plus=(key:string,n:number)=>{const d=new Date(`${key}T12:00:00`);d.setDate(d.getDate()+n);return getLocalDateKey(d)};
const shiftMonth=(key:string,delta:number)=>{const d=new Date(`${key}T12:00:00`);return getLocalDateKey(new Date(d.getFullYear(),d.getMonth()+delta,1,12))};
export default function CalendarScreen(){const{isDark}=useTheme();const today=getLocalDateKey();const[date,setDate]=useState(today);const[view,setView]=useState<'Day'|'Week'|'Month'>('Day');const[items,setItems]=useState<PlanEntry[]>([]);const[modal,setModal]=useState(false);const[title,setTitle]=useState('');const[time,setTime]=useState('');
const load=useCallback(async()=>{const p=await getPlanForDate(date);setItems(p)},[date]);useFocusEffect(useCallback(()=>{void load()},[load]));const dark=isDark;const text=dark?'#fff':'#151C45';
const toggle=async(i:PlanEntry)=>{if(i.kind==='habit'&&i.habitId)await setHabitCompletion(i.habitId,date,!i.completed);if(i.kind==='task'&&i.taskId)await setPlannedItemCompleted(i.taskId,date,!i.completed);await load()};
const save=async()=>{const clean=title.trim();if(!clean)return Alert.alert('Add a name','Enter a name for this task.');await addPlannedItem({id:makeId('task'),title:clean,date,time,reminderEnabled:false});setTitle('');setTime('');setModal(false);await load()};
return <View style={[s.page,{backgroundColor:dark?'#0A102C':'#F4F6FF'}]}><ScrollView contentContainerStyle={s.body}><Text style={[s.title,{color:text}]}>Calendar</Text><View style={s.switch}>{(['Day','Week','Month'] as const).map(v=><Pressable key={v} onPress={()=>setView(v)} style={[s.pill,view===v&&s.active]}><Text style={{color:view===v?'white':text,fontWeight:'700'}}>{v}</Text></Pressable>)}</View>
{view==='Day'&&<><View style={s.dateRow}><Pressable onPress={()=>setDate(plus(date,-1))}><Text style={s.nav}>‹</Text></Pressable><Pressable onPress={()=>setDate(today)}><Text style={[s.dateText,{color:text}]}>{date===today?'Today':new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</Text></Pressable><Pressable onPress={()=>setDate(plus(date,1))}><Text style={s.nav}>›</Text></Pressable></View><View style={s.timeline}>{items.length?items.map(i=><Pressable key={i.id} onPress={()=>toggle(i)} onLongPress={()=>i.taskId&&Alert.alert('Delete task?',i.title,[{text:'Cancel'},{text:'Delete',style:'destructive',onPress:async()=>{await deletePlannedItem(i.taskId!);load()}}])} style={[s.entry,{backgroundColor:dark?'#141D42':'white'}]}><View style={[s.dot,{backgroundColor:i.color||'#4B73FF'}]}/><Text style={s.time}>{i.time||'Any time'}</Text><View style={{flex:1}}><Text style={[s.entryTitle,{color:text,textDecorationLine:i.completed?'line-through':'none'}]}>{i.title}</Text><Text style={s.meta}>{i.kind==='task'?'Task':i.kind==='habit'?'Habit':'Affirmation'}</Text></View><Text style={{fontSize:18,color:i.completed?'#1BAC82':'#A7B1C9'}}>{i.completed?'✓':'○'}</Text></Pressable>):<Text style={s.empty}>Nothing planned yet. Add a task or set up a habit.</Text>}</View></>}
{view==='Week'&&<View>{Array.from({length:7},(_,n)=>plus(date,n-new Date(`${date}T12:00:00`).getDay())).map((key,index)=><Pressable key={key} onPress={()=>{setDate(key);setView('Day')}} style={[s.weekRow,{backgroundColor:dark?'#141D42':'white'}]}><Text style={s.meta}>{new Date(`${key}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</Text><Text style={{color:text,fontWeight:'650'}}>{key===today?'Today':key}</Text><Text style={s.meta}>›</Text></Pressable>)}</View>}
{view==='Month'&&<><View style={s.monthHead}><Pressable onPress={()=>setDate(shiftMonth(date,-1))}><Text style={s.nav}>‹</Text></Pressable><Text style={[s.dateText,{color:text}]}>{new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</Text><Pressable onPress={()=>setDate(shiftMonth(date,1))><Text style={s.nav}>›</Text></Pressable></View><View style={s.grid}>{days.map((d,i)=><Text key={i} style={s.dayLabel}>{d}</Text>)}{(()=>{const d=new Date(`${date}T12:00:00`);const start=new Date(d.getFullYear(),d.getMonth(),1).getDay();const count=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();return [...Array(start).fill(null),...Array.from({length:count},(_,i)=>i+1)].map((day,i)=>{const key=day?getLocalDateKey(new Date(d.getFullYear(),d.getMonth(),day,12)):'';return <Pressable key={i} disabled={!day} onPress={()=>{setDate(key);setView('Day')}} style={[s.cell,day&&key===date&&s.selected]}><Text style={{color:key===date?'white':text,fontWeight:key===today?'800':'500'}}>{day||''}</Text></Pressable>})})()}</View></>}
<Pressable onPress={()=>{setTitle('');setTime('');setModal(true)}} style={s.add}><Text style={s.addText}>＋ Add one-time task</Text></Pressable></ScrollView><Modal visible={modal} transparent animationType="slide" onRequestClose={()=>setModal(false)}><View style={s.scrim}><View style={s.sheet}><Text style={[s.title,{color:text,fontSize:23}]}>New task</Text><Text style={s.meta}>For {date}</Text><TextInput value={title} onChangeText={setTitle} placeholder="What do you need to do?" placeholderTextColor="#8A93AE" style={s.input}/><TextInput value={time} onChangeText={setTime} placeholder="Time (optional, e.g. 14:30)" placeholderTextColor="#8A93AE" style={s.input}/><Pressable style={s.add} onPress={save}><Text style={s.addText}>Add to calendar</Text></Pressable><Pressable onPress={()=>setModal(false)}><Text style={[s.meta,{textAlign:'center',padding:12}]}>Cancel</Text></Pressable></View></View></Modal></View>}
const s=StyleSheet.create({page:{flex:1},body:{padding:20,paddingBottom:115},title:{fontSize:32,fontWeight:'800',marginBottom:18},switch:{flexDirection:'row',backgroundColor:'#E7EAF6',padding:4,borderRadius:13},pill:{flex:1,alignItems:'center',padding:10,borderRadius:10},active:{backgroundColor:'#426CFF'},dateRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginVertical:22},dateText:{fontSize:17,fontWeight:'700'},nav:{fontSize:30,color:'#456AFF',paddingHorizontal:9},timeline:{gap:9},entry:{borderRadius:15,padding:14,flexDirection:'row',alignItems:'center',gap:10},dot:{width:9,height:9,borderRadius:5},time:{width:62,fontSize:12,color:'#8791AF'},entryTitle:{fontSize:14,fontWeight:'700'},meta:{fontSize:12,color:'#8C96B3',marginTop:4},empty:{padding:20,textAlign:'center',color:'#8490B0'},add:{backgroundColor:'#426CFF',borderRadius:14,padding:15,alignItems:'center',marginTop:18},addText:{color:'white',fontWeight:'750',fontSize:15},weekRow:{padding:16,borderRadius:14,marginTop:8,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},monthHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginVertical:16},grid:{flexDirection:'row',flexWrap:'wrap'},dayLabel:{width:'14.28%',textAlign:'center',color:'#8893B0',padding:8,fontWeight:'700'},cell:{width:'14.28%',aspectRatio:1,alignItems:'center',justifyContent:'center',borderRadius:30},selected:{backgroundColor:'#426CFF'},scrim:{flex:1,backgroundColor:'#0008',justifyContent:'flex-end'},sheet:{backgroundColor:'#fff',padding:22,paddingBottom:35,borderTopLeftRadius:25,borderTopRightRadius:25},input:{borderWidth:1,borderColor:'#DCE1EF',borderRadius:12,padding:13,color:'#141A3E',marginTop:13}});
