
// Top 500 default affirmations for offline use
export const DEFAULT_AFFIRMATIONS = [
  "I am worthy of love and respect.",
  "I choose to be happy and grateful today.",
  "I am capable of achieving my goals.",
  "I trust in my ability to overcome challenges.",
  "I am growing and learning every day.",
  "I deserve success and abundance.",
  "I am confident in my decisions.",
  "I radiate positivity and kindness.",
  "I am in control of my thoughts and emotions.",
  "I embrace change and new opportunities.",
  "I am enough, just as I am.",
  "I attract positive energy into my life.",
  "I am resilient and strong.",
  "I believe in my dreams and abilities.",
  "I am grateful for all that I have.",
  "I choose peace over worry.",
  "I am creating the life I desire.",
  "I am surrounded by love and support.",
  "I trust the journey of my life.",
  "I am proud of how far I've come.",
  "Every day I become a better version of myself.",
  "I release all negativity and embrace positivity.",
  "I am deserving of all good things.",
  "My potential is limitless.",
  "I choose to focus on what I can control.",
  "I am at peace with my past.",
  "I welcome abundance into my life.",
  "I am worthy of my dreams.",
  "I trust my intuition and inner wisdom.",
  "I am creating positive change in my life.",
  "I am confident in who I am becoming.",
  "I let go of what no longer serves me.",
  "I am open to receiving love and joy.",
  "I honor my needs and boundaries.",
  "I am patient with myself and my progress.",
  "I celebrate my unique qualities.",
  "I am capable of handling whatever comes my way.",
  "I choose to see the good in every situation.",
  "I am worthy of rest and relaxation.",
  "I trust that everything happens for a reason.",
  "I am grateful for my body and all it does for me.",
  "I am becoming more confident each day.",
  "I deserve to be treated with kindness.",
  "I am proud of my accomplishments.",
  "I choose to focus on solutions, not problems.",
  "I am worthy of financial abundance.",
  "I trust in the timing of my life.",
  "I am surrounded by opportunities.",
  "I choose to be optimistic about my future.",
  "I am capable of learning new things.",
  "I release fear and embrace courage.",
  "I am worthy of healthy relationships.",
  "I trust myself to make good decisions.",
  "I am grateful for this moment.",
  "I choose to be kind to myself.",
  "I am worthy of success in all areas of my life.",
  "I trust that I am exactly where I need to be.",
  "I am open to new possibilities.",
  "I choose to let go of perfectionism.",
  "I am worthy of love just as I am.",
  "I trust in my ability to create the life I want.",
  "I am grateful for the lessons I've learned.",
  "I choose to focus on progress, not perfection.",
  "I am worthy of taking up space.",
  "I trust that good things are coming my way.",
  "I am capable of achieving balance in my life.",
  "I choose to be present in this moment.",
  "I am worthy of pursuing my passions.",
  "I trust in my resilience and strength.",
  "I am grateful for the people in my life.",
  "I choose to see challenges as opportunities.",
  "I am worthy of expressing my true self.",
  "I trust that I have everything I need within me.",
  "I am capable of overcoming obstacles.",
  "I choose to be compassionate with myself.",
  "I am worthy of achieving my goals.",
  "I trust in the process of growth.",
  "I am grateful for my unique journey.",
  "I choose to focus on what brings me joy.",
  "I am worthy of living authentically.",
  "I trust that I am making progress.",
  "I am capable of creating meaningful connections.",
  "I choose to release self-doubt.",
  "I am worthy of experiencing peace.",
  "I trust in my ability to adapt.",
  "I am grateful for new beginnings.",
  "I choose to embrace my imperfections.",
  "I am worthy of self-care and self-love.",
  "I trust that I am on the right path.",
  "I am capable of manifesting my desires.",
  "I choose to be gentle with myself.",
  "I am worthy of happiness and fulfillment.",
  "I trust in the wisdom of my heart.",
  "I am grateful for the present moment.",
  "I choose to let go of comparison.",
  "I am worthy of respect and dignity.",
  "I trust that I am enough.",
  "I am capable of creating positive change.",
  "I choose to focus on my strengths.",
  "I am worthy of living my best life.",
  "I trust in my ability to heal.",
  "I am grateful for my resilience.",
  "I choose to be open to love.",
  "I am worthy of forgiveness.",
  "I trust that better days are ahead.",
  "I am capable of achieving inner peace.",
  "I choose to honor my feelings.",
  "I am worthy of pursuing my dreams.",
  "I trust in the power of positive thinking.",
  "I am grateful for my growth.",
  "I choose to be patient with my journey.",
  "I am worthy of experiencing joy.",
  "I trust that I am supported.",
  "I am capable of creating the life I envision.",
  "I choose to release limiting beliefs.",
  "I am worthy of abundance in all forms.",
  "I trust in my ability to persevere.",
  "I am grateful for my courage.",
  "I choose to embrace uncertainty.",
  "I am worthy of living with purpose.",
  "I trust that I am guided.",
  "I am capable of making a difference.",
  "I choose to be true to myself.",
  "I am worthy of experiencing freedom.",
  "I trust in the journey ahead.",
  "I am grateful for my wisdom.",
  "I choose to focus on possibilities.",
  "I am worthy of self-acceptance.",
  "I trust that I am loved.",
  "I am capable of achieving my potential.",
  "I choose to be hopeful.",
  "I am worthy of living fully.",
  "I trust in my inner strength.",
  "I am grateful for my experiences.",
  "I choose to embrace change.",
  "I am worthy of compassion.",
  "I trust that I am growing.",
  "I am capable of finding solutions.",
  "I choose to be confident.",
  "I am worthy of peace of mind.",
  "I trust in my journey.",
  "I am grateful for my blessings.",
  "I choose to be resilient.",
  "I am worthy of self-expression.",
  "I trust that I am capable.",
  "I am creating a life I love.",
  "I choose to be empowered.",
  "I am worthy of my aspirations.",
  "I trust in my abilities.",
  "I am grateful for my determination.",
  "I choose to be authentic.",
  "I am worthy of living with intention.",
  "I trust that I am deserving.",
  "I am capable of achieving clarity.",
  "I choose to be mindful.",
  "I am worthy of experiencing contentment.",
  "I trust in my path.",
  "I am grateful for my strength.",
  "I choose to be brave.",
  "I am worthy of self-discovery.",
  "I trust that I am evolving.",
  "I am capable of creating harmony.",
  "I choose to be present.",
  "I am worthy of living with grace.",
  "I trust in my potential.",
  "I am grateful for my journey.",
  "I choose to be positive.",
  "I am worthy of self-respect.",
  "I trust that I am worthy.",
  "I am capable of achieving wellness.",
  "I choose to be grateful.",
  "I am worthy of experiencing love.",
  "I trust in my growth.",
  "I am grateful for my life.",
  "I choose to be kind.",
  "I am worthy of living with joy.",
  "I trust that I am blessed.",
  "I am capable of creating beauty.",
  "I choose to be loving.",
  "I am worthy of self-compassion.",
  "I trust in my heart.",
  "I am grateful for my gifts.",
  "I choose to be peaceful.",
  "I am worthy of living with purpose.",
  "I trust that I am whole.",
  "I am capable of achieving balance.",
  "I choose to be centered.",
  "I am worthy of experiencing serenity.",
  "I trust in my wisdom.",
  "I am grateful for my talents.",
  "I choose to be calm.",
  "I am worthy of self-trust.",
  "I trust that I am complete.",
  "I am capable of creating joy.",
  "I choose to be understanding.",
  "I am worthy of living with ease.",
  "I trust in my journey of self-discovery.",
  "I am grateful for my progress.",
  "I choose to be accepting.",
  "I am worthy of experiencing harmony.",
  "I trust that I am valued.",
  "I am capable of achieving my vision.",
  "I choose to be forgiving.",
  "I am worthy of living with confidence.",
  "I trust in my inner guidance.",
  "I am grateful for my opportunities.",
  "I choose to be supportive of myself.",
  "I am worthy of self-belief.",
  "I trust that I am powerful.",
  "I am capable of creating abundance.",
  "I choose to be encouraging.",
  "I am worthy of experiencing success.",
  "I trust in my capabilities.",
  "I am grateful for my resilience.",
  "I choose to be optimistic.",
  "I am worthy of living with clarity.",
  "I trust that I am strong.",
  "I am capable of achieving my dreams.",
  "I choose to be patient.",
  "I am worthy of experiencing peace.",
  "I trust in my process.",
  "I am grateful for my courage.",
  "I choose to be gentle.",
  "I am worthy of self-kindness.",
  "I trust that I am enough.",
  "I am capable of creating positive energy.",
  "I choose to be compassionate.",
  "I am worthy of living with love.",
  "I trust in my transformation.",
  "I am grateful for my healing.",
  "I choose to be nurturing.",
  "I am worthy of experiencing fulfillment.",
  "I trust that I am capable of greatness.",
  "I am creating my own happiness.",
  "I choose to be empowered by my choices.",
  "I am worthy of all the good things life has to offer.",
  "I trust in the universe to guide me.",
  "I am grateful for the abundance that surrounds me.",
  "I choose to see beauty in everything.",
  "I am worthy of living a life of passion.",
  "I trust that my dreams are within reach.",
  "I am capable of turning my vision into reality.",
  "I choose to be inspired by life.",
  "I am worthy of experiencing wonder.",
  "I trust in the magic of new beginnings.",
  "I am grateful for the gift of today.",
  "I choose to be open to miracles.",
  "I am worthy of living with enthusiasm.",
  "I trust that I am exactly where I'm meant to be.",
  "I am capable of creating my own path.",
  "I choose to be adventurous.",
  "I am worthy of experiencing excitement.",
  "I trust in the power of my intentions.",
  "I am grateful for my unique perspective.",
  "I choose to be curious about life.",
  "I am worthy of self-empowerment.",
  "I trust that I am making a difference.",
  "I am capable of achieving extraordinary things.",
  "I choose to be bold.",
  "I am worthy of living with vitality.",
  "I trust in my creative power.",
  "I am grateful for my imagination.",
  "I choose to be innovative.",
  "I am worthy of experiencing inspiration.",
  "I trust that I am a force for good.",
  "I am capable of creating meaningful impact.",
  "I choose to be purposeful.",
  "I am worthy of living with passion.",
  "I trust in my ability to inspire others.",
  "I am grateful for my influence.",
  "I choose to be a light in the world.",
  "I am worthy of self-celebration.",
  "I trust that I am making progress every day.",
  "I am capable of achieving mastery.",
  "I choose to be dedicated.",
  "I am worthy of experiencing excellence.",
  "I trust in my commitment to growth.",
  "I am grateful for my discipline.",
  "I choose to be focused.",
  "I am worthy of living with determination.",
  "I trust that I am unstoppable.",
  "I am capable of overcoming any challenge.",
  "I choose to be persistent.",
  "I am worthy of experiencing victory.",
  "I trust in my ability to succeed.",
  "I am grateful for my perseverance.",
  "I choose to be tenacious.",
  "I am worthy of self-motivation.",
  "I trust that I am driven by purpose.",
  "I am capable of achieving remarkable results.",
  "I choose to be ambitious.",
  "I am worthy of living with drive.",
  "I trust in my passion for life.",
  "I am grateful for my energy.",
  "I choose to be enthusiastic.",
  "I am worthy of experiencing momentum.",
  "I trust that I am moving forward.",
  "I am capable of creating lasting change.",
  "I choose to be transformative.",
  "I am worthy of living with impact.",
  "I trust in my ability to make a difference.",
  "I am grateful for my contribution.",
  "I choose to be significant.",
  "I am worthy of self-recognition.",
  "I trust that I am valued for who I am.",
  "I am capable of achieving recognition.",
  "I choose to be proud of myself.",
  "I am worthy of experiencing appreciation.",
  "I trust in my worthiness.",
  "I am grateful for my self-worth.",
  "I choose to be confident in my value.",
  "I am worthy of living with dignity.",
  "I trust that I am respected.",
  "I am capable of commanding respect.",
  "I choose to be honorable.",
  "I am worthy of experiencing integrity.",
  "I trust in my moral compass.",
  "I am grateful for my values.",
  "I choose to be principled.",
  "I am worthy of self-honor.",
  "I trust that I am guided by my values.",
  "I am capable of living authentically.",
  "I choose to be genuine.",
  "I am worthy of experiencing authenticity.",
  "I trust in my true self.",
  "I am grateful for my individuality.",
  "I choose to be unique.",
  "I am worthy of living as myself.",
  "I trust that I am accepted for who I am.",
  "I am capable of being my best self.",
  "I choose to be real.",
  "I am worthy of experiencing freedom to be myself.",
  "I trust in my self-expression.",
  "I am grateful for my voice.",
  "I choose to be heard.",
  "I am worthy of self-advocacy.",
  "I trust that I can speak my truth.",
  "I am capable of expressing my needs.",
  "I choose to be assertive.",
  "I am worthy of experiencing empowerment.",
  "I trust in my personal power.",
  "I am grateful for my agency.",
  "I choose to be in control of my life.",
  "I am worthy of living with autonomy.",
  "I trust that I am the author of my story.",
  "I am capable of creating my destiny.",
  "I choose to be the master of my fate.",
  "I am worthy of experiencing sovereignty.",
  "I trust in my independence.",
  "I am grateful for my freedom.",
  "I choose to be liberated.",
  "I am worthy of self-determination.",
  "I trust that I am free to choose.",
  "I am capable of making my own decisions.",
  "I choose to be self-directed.",
  "I am worthy of living on my own terms.",
  "I trust in my ability to chart my course.",
  "I am grateful for my choices.",
  "I choose to be responsible for my life.",
  "I am worthy of experiencing self-mastery.",
  "I trust that I am in charge of my happiness.",
  "I am capable of creating my own joy.",
  "I choose to be the source of my happiness.",
  "I am worthy of living with self-sufficiency.",
  "I trust in my resourcefulness.",
  "I am grateful for my capabilities.",
  "I choose to be self-reliant.",
  "I am worthy of experiencing independence.",
  "I trust that I can handle anything.",
  "I am capable of solving my own problems.",
  "I choose to be solution-oriented.",
  "I am worthy of living with confidence in myself.",
  "I trust in my problem-solving abilities.",
  "I am grateful for my intelligence.",
  "I choose to be wise.",
  "I am worthy of self-trust.",
  "I trust that I know what's best for me.",
  "I am capable of making wise choices.",
  "I choose to be discerning.",
  "I am worthy of experiencing clarity of mind.",
  "I trust in my judgment.",
  "I am grateful for my insight.",
  "I choose to be perceptive.",
  "I am worthy of living with awareness.",
  "I trust that I am conscious of my choices.",
  "I am capable of being mindful.",
  "I choose to be present in my life.",
  "I am worthy of experiencing mindfulness.",
  "I trust in my awareness.",
  "I am grateful for my consciousness.",
  "I choose to be awake to life.",
  "I am worthy of self-awareness.",
  "I trust that I understand myself.",
  "I am capable of self-reflection.",
  "I choose to be introspective.",
  "I am worthy of experiencing self-knowledge.",
  "I trust in my self-understanding.",
  "I am grateful for my self-insight.",
  "I choose to be self-aware.",
  "I am worthy of living with self-knowledge.",
  "I trust that I know who I am.",
  "I am capable of understanding my needs.",
  "I choose to be in tune with myself.",
  "I am worthy of experiencing self-connection.",
  "I trust in my relationship with myself.",
  "I am grateful for my self-love.",
  "I choose to be loving toward myself.",
  "I am worthy of self-care.",
  "I trust that I deserve to take care of myself.",
  "I am capable of nurturing myself.",
  "I choose to be kind to myself.",
  "I am worthy of experiencing self-compassion.",
  "I trust in my ability to comfort myself.",
  "I am grateful for my self-support.",
  "I choose to be my own best friend.",
  "I am worthy of living with self-love.",
  "I trust that I am my own greatest ally.",
  "I am capable of being there for myself.",
  "I choose to be supportive of myself.",
  "I am worthy of experiencing self-acceptance.",
  "I trust in my ability to accept myself.",
  "I am grateful for my self-embrace.",
  "I choose to embrace all of who I am.",
  "I am worthy of self-forgiveness.",
  "I trust that I can forgive myself.",
  "I am capable of letting go of self-judgment.",
  "I choose to be free from self-criticism.",
  "I am worthy of experiencing self-peace.",
  "I trust in my ability to be at peace with myself.",
  "I am grateful for my self-harmony.",
  "I choose to be in harmony with myself.",
  "I am worthy of living with self-contentment.",
  "I trust that I am satisfied with who I am.",
  "I am capable of being happy with myself.",
  "I choose to be content with my journey.",
  "I am worthy of experiencing self-satisfaction.",
  "I trust in my completeness.",
  "I am grateful for being whole.",
  "I choose to be complete as I am.",
  "I am worthy of self-wholeness.",
  "I trust that I am already complete.",
  "I am capable of recognizing my wholeness.",
  "I choose to see myself as whole.",
  "I am worthy of experiencing unity within myself.",
  "I trust in my inner harmony.",
  "I am grateful for my integration.",
  "I choose to be integrated.",
  "I am worthy of living with inner peace.",
  "I trust that I am at peace within.",
  "I am capable of finding peace within myself.",
  "I choose to be peaceful.",
  "I am worthy of experiencing tranquility.",
  "I trust in my inner calm.",
  "I am grateful for my serenity.",
  "I choose to be serene.",
  "I am worthy of self-tranquility.",
  "I trust that I am calm within.",
  "I am capable of maintaining inner peace.",
  "I choose to be centered in peace.",
  "I am worthy of living with equanimity.",
  "I trust in my balance.",
  "I am grateful for my equilibrium.",
  "I choose to be balanced.",
  "I am worthy of experiencing stability.",
  "I trust that I am grounded.",
  "I am capable of staying grounded.",
  "I choose to be rooted in myself.",
  "I am worthy of self-stability.",
  "I trust in my foundation.",
  "I am grateful for my roots.",
  "I choose to be anchored.",
  "I am worthy of living with security.",
  "I trust that I am safe within myself.",
  "I am capable of creating inner safety.",
  "I choose to feel safe.",
  "I am worthy of experiencing inner security.",
  "I trust in my inner sanctuary.",
  "I am grateful for my safe space within.",
  "I choose to honor my inner sanctuary.",
  "I am worthy of self-protection.",
  "I trust that I can protect my peace.",
  "I am capable of setting healthy boundaries.",
  "I choose to protect my energy.",
  "I am worthy of living with boundaries.",
  "I trust in my right to say no.",
  "I am grateful for my boundaries.",
  "I choose to honor my limits.",
  "I am worthy of self-preservation.",
  "I trust that I can take care of my needs.",
];

export function getRandomAffirmation(): string {
  const randomIndex = Math.floor(Math.random() * DEFAULT_AFFIRMATIONS.length);
  return DEFAULT_AFFIRMATIONS[randomIndex];
}

export function getMultipleRandomAffirmations(count: number): string[] {
  const shuffled = [...DEFAULT_AFFIRMATIONS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, Math.min(count, DEFAULT_AFFIRMATIONS.length));
}
